"""empty message

Revision ID: 4a1a53873a38
Revises: 
Create Date: 2021-06-26 13:41:57.781832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1a53873a38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('manager', 'super'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('task_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('langs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('creator_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_admin_id'], ['admins.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_langs_creator_admin_id'), 'langs', ['creator_admin_id'], unique=False)
    op.create_index(op.f('ix_langs_name'), 'langs', ['name'], unique=True)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('creator_admin_id', sa.Integer(), nullable=True),
    sa.Column('lang_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_admin_id'], ['admins.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lang_id'], ['langs.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_creator_admin_id'), 'courses', ['creator_admin_id'], unique=False)
    op.create_index(op.f('ix_courses_lang_id'), 'courses', ['lang_id'], unique=False)
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('creator_admin_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_admin_id'], ['admins.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_course_id'), 'topics', ['course_id'], unique=False)
    op.create_index(op.f('ix_topics_creator_admin_id'), 'topics', ['creator_admin_id'], unique=False)
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('creator_admin_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_admin_id'], ['admins.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_creator_admin_id'), 'lessons', ['creator_admin_id'], unique=False)
    op.create_index(op.f('ix_lessons_topic_id'), 'lessons', ['topic_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('mp4', 'mp3', 'png', 'jpg', 'gif', 'pdf', 'svg'), nullable=True),
    sa.Column('file_path', sa.String(length=2083), nullable=True),
    sa.Column('topic_picture_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_picture_fk'], ['topics.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_name'), 'media', ['name'], unique=False)
    op.create_index(op.f('ix_media_topic_picture_fk'), 'media', ['topic_picture_fk'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('elements', sa.JSON(), nullable=True),
    sa.Column('right_sentences', sa.JSON(), nullable=True),
    sa.Column('wrong_sentences', sa.JSON(), nullable=True),
    sa.Column('media', sa.JSON(), nullable=True),
    sa.Column('task_type_id', sa.Integer(), nullable=True),
    sa.Column('creator_admin_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_admin_id'], ['admins.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_types.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_creator_admin_id'), 'tasks', ['creator_admin_id'], unique=False)
    op.create_index(op.f('ix_tasks_lesson_id'), 'tasks', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_tasks_task_type_id'), 'tasks', ['task_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_task_type_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_lesson_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_creator_admin_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_media_topic_picture_fk'), table_name='media')
    op.drop_index(op.f('ix_media_name'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_lessons_topic_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_creator_admin_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_index(op.f('ix_topics_creator_admin_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_course_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_lang_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_creator_admin_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_langs_name'), table_name='langs')
    op.drop_index(op.f('ix_langs_creator_admin_id'), table_name='langs')
    op.drop_table('langs')
    op.drop_table('task_types')
    op.drop_table('admins')
    # ### end Alembic commands ###
