"""empty message

Revision ID: 4b06b080580d
Revises: 352e784a8eb9
Create Date: 2021-07-18 18:40:05.995438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b06b080580d'
down_revision = '352e784a8eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('task_video_fk', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_media_task_video_fk'), 'media', ['task_video_fk'], unique=False)
    op.create_foreign_key(None, 'media', 'tasks', ['task_video_fk'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('tasks', sa.Column('video_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'media', ['video_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'video_id')
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_index(op.f('ix_media_task_video_fk'), table_name='media')
    op.drop_column('media', 'task_video_fk')
    # ### end Alembic commands ###
