"""empty message

Revision ID: 5af496d91584
Revises: 970c477a71ad
Create Date: 2021-07-30 19:21:36.691479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af496d91584'
down_revision = '970c477a71ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('word_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_word_id'), 'tasks', ['word_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'words', ['word_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_word_id'), table_name='tasks')
    op.drop_column('tasks', 'word_id')
    # ### end Alembic commands ###
