"""empty message

Revision ID: 5d7fe97e2d07
Revises: 7abc08c97e8d
Create Date: 2021-06-25 16:20:28.070319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7fe97e2d07'
down_revision = '7abc08c97e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'langs', ['lang_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'topics', ['topic_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'lessons', 'admins', ['creator_admin_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'admins', ['creator_admin_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'topics', 'courses', ['course_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'admins', ['creator_admin_id'], ['id'])
    op.create_foreign_key(None, 'topics', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'topics', ['topic_id'], ['id'])
    op.create_foreign_key(None, 'lessons', 'admins', ['creator_admin_id'], ['id'])
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'langs', ['lang_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###
